server:
  port: 9289

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:127.0.0.1}:${DB_PORT:5432}/${DB_NAME:postgres}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  servlet:
    multipart:
      max-file-size: 1024MB

oss:
  endpoint: ${OSS_ENDPOINT}
  region: ${OSS_REGION}
  accessKey: ${OSS_ACCESSKEY}
  secretKey: ${OSS_SECRETKEY}
  isHttps: false
  domain: http://localhost:9000

